src/main/java/cz/zcu/kiv/pia/martinm/internetbanking/domain/Account.java
package cz.zcu.kiv.pia.martinm.internetbanking.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import cz.zcu.kiv.pia.martinm.internetbanking.service.CurrencyUtils;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * Account entity.
 *
 * Date: 20.12.2018
 *
 * @author Martin Matas
 */
@ToString(onlyExplicitlyIncluded = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Entity
@Table(name = "Account")
public class Account implements DataTransferObject<Integer> {

    public Account() {
    }

    /**
     * Creates new account.
     *
     * @param currency - account's currency
     * @param accountNumber - account number
     * @param cardNumber - card number
     * @param user - account's owner
     */
    public Account(String currency, String accountNumber, String cardNumber, User user) {
        this.currency = currency;
        this.accountNumber = accountNumber;
        this.cardNumber = cardNumber;
        this.balance = new BigDecimal(0);
        this.user = user;
    }

    /**
     * Account's identifier.
     */
    @Id
        @Column(nullable = false, name = "ID")
        @ToString.Include
        @EqualsAndHashCode.Include
        @GeneratedValue(strategy = GenerationType.SEQUENCE)
        private Integer id;

    /**
     * Account's currency.
     */
    @Column(nullable = false, name = "Currency")
    private String currency;

    /**
     * Account's number.
     */
    @Column(nullable = false, name = "AccountNumber")
        private String accountNumber;

    /**
     * Card number assigned to this account.
     */
    @Column(nullable = false, name = "CardNumber")
        private String cardNumber;

    /**
     * Account's actual balance.
     */
    @Column(nullable = false, name = "Balance")
        private BigDecimal balance;

    /**
     * Account's owner.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "User_ID")
    @JsonIgnore
        private User user;

    // Mappings

    @Override
    public Integer getId() {
        return id;
    }

    public String getCurrency() {
        return currency;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    @Transient
    public String getFormatedBalance() {
        return CurrencyUtils.format(balance, currency);
    }

    public User getUser() {
        return user;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
}

src/main/webapp/WEB-INF/templates/ib/create_transaction.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<layout:extends name="../base.jsp">
    <layout:put block="title" type="REPLACE">
        <title><spring:message code="ib.transaction.title" /></title>
    </layout:put>

    <layout:put block="styles">
    </layout:put>

    <layout:put block="content">

        <jsp:include page="ib_nav.jsp" />

        <div class="container-fluid lb-content-wrapper">
            <div class="container">
                <div class="row justify-content-center">
                    <form:form class="col-lg-10 col-12 align-self-center" action="/ib/create-transaction" method="post" modelAttribute="newTransaction" >
                        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                        <div class="form-row">
                            <div class="form-group col-12">
                                <div class="form-group">
                                    <label for="transactionTemplate"><spring:message code="transaction.create.form.template" /></label>
                                    <select id="transactionTemplate">
                                        <option value="">--</option>
                                        <c:forEach var="template" items="${templates}">
                                            <option value="${template.id}">${template.templateName}</option>
                                        </c:forEach>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group col-md-5 col-12">
                                <div class="h3"><spring:message code="transaction.create.form.paymentSettings" /></div>
                                <div class="form-group">
                                    <form:label path="senderAccountNumber"><spring:message code="transaction.create.form.senderAccountRequired" /></form:label><form:errors class="formError" path='senderAccountNumber' />
                                    <form:select class="form-control" items="${accounts}" path="senderAccountNumber" required="required" />
                                </div>
                                <div class="form-group">
                                    <form:label path="receiverAccountNumber"><spring:message code="transaction.create.form.receiverAccountRequired" /></form:label><form:errors class="formError" path='receiverAccountNumber' />
                                    <form:input type="text" class="form-control" path="receiverAccountNumber" required="required" pattern="^(([0-9]{6})-)?([0-9]{10})(/[0-9]{4})$" />
                                </div>
                                <div class="form-group">
                                    <form:label path="sentAmount"><spring:message code="transaction.create.form.amountRequired" /></form:label><form:errors class="formError" path='sentAmount' />
                                    <form:input type="number" class="form-control" path="sentAmount" required="required" min="1" />
                                </div>
                                <div class="form-group">
                                    <form:label path="dueDate"><spring:message code="transaction.create.form.dueDate" /></form:label><form:errors class="formError" path='dueDate' />
                                    <form:input type="date" class="form-control" path="dueDate" />
                                </div>
                            </div>
                            <div class="form-group col-md-5 offset-md-2 col-12">
                                <div class="h3"><spring:message code="transaction.create.form.additionalData" /></div>
                                <div class="form-group">
                                    <form:label path="constantSymbol"><spring:message code="transaction.create.form.constantSymbol" /></form:label><form:errors class="formError" path='constantSymbol' />
                                    <form:input type="text" class="form-control" path="constantSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="variableSymbol"><spring:message code="transaction.create.form.variableSymbol" /></form:label><form:errors class="formError" path='variableSymbol' />
                                    <form:input type="text" class="form-control" path="variableSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="specificSymbol"><spring:message code="transaction.create.form.specificSymbol" /></form:label><form:errors class="formError" path='specificSymbol' />
                                    <form:input type="text" class="form-control" path="specificSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="message"><spring:message code="transaction.create.form.message" /></form:label><form:errors class="formError" path='message' />
                                    <form:input type="text" class="form-control" path="message" maxlength="255" />
                                </div>
                            </div>
                            <div class="form-group col-12 text-center mt-sm-5">
                                <spring:message code="transaction.create.form.performPayment" var="performPaymentLabel" />
                                <button type="submit" class="btn btn-primary">${performPaymentLabel}</button>
                            </div>
                        </div>
                    </form:form>
                </div>
            </div>
        </div>

    </layout:put>

    <layout:put block="scripts">
        <script src="/js/async_templates.js"></script>
    </layout:put>
</layout:extends>

src/main/webapp/WEB-INF/templates/ib/edit_template.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<layout:extends name="../base.jsp">
    <layout:put block="title" type="REPLACE">
        <title><spring:message code="ib.template.edit.title" /></title>
    </layout:put>

    <layout:put block="styles">
        <link rel="stylesheet" href="/css/account.css">
    </layout:put>

    <layout:put block="content">

        <jsp:include page="ib_nav.jsp" />

        <div class="container-fluid lb-content-wrapper">
            <div class="container">
                <div class="row justify-content-center mt-5">
                    <div class="col-lg-10 col-12 align-self-center h3"><spring:message code="template.edit.form.label" /></div>
                    <form:form class="col-lg-10 col-12 align-self-center" action="/ib/templates/modify" method="post" modelAttribute="modifyTemplate" >
                        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                        <div class="form-row">
                            <div class="form-group col-12">
                                <div class="form-group">
                                    <form:label path="templateName"><spring:message code="template.form.templateNameRequired" /></form:label><form:errors class="formError" path='templateName' />
                                    <form:input type="text" class="form-control" path="templateName" required="required" />
                                </div>
                            </div>
                            <div class="form-group col-md-5 col-12">
                                <div class="h4"><spring:message code="template.form.paymentSettings" /></div>
                                <div class="form-group">
                                    <form:label path="senderAccountNumber"><spring:message code="template.form.senderAccountRequired" /></form:label><form:errors class="formError" path='senderAccountNumber' />
                                    <form:select class="form-control" items="${accounts}" path="senderAccountNumber" required="required" />
                                </div>
                                <div class="form-group">
                                    <form:label path="receiverAccountNumber"><spring:message code="template.form.receiverAccountRequired" /></form:label><form:errors class="formError" path='receiverAccountNumber' />
                                    <form:input type="text" class="form-control" path="receiverAccountNumber" required="required" pattern="^(([0-9]{6})-)?([0-9]{10})(/[0-9]{4})$" />
                                </div>
                                <div class="form-group">
                                    <form:label path="sentAmount"><spring:message code="template.form.amountRequired" /></form:label><form:errors class="formError" path='sentAmount' />
                                    <form:input type="number" class="form-control" path="sentAmount" required="required" min="1" />
                                </div>
                                <div class="form-group">
                                    <form:label path="dueDate"><spring:message code="template.form.dueDate" /></form:label><form:errors class="formError" path='dueDate' />
                                    <form:input type="date" class="form-control" path="dueDate" />
                                </div>
                            </div>
                            <div class="form-group col-md-5 offset-md-2 col-12">
                                <div class="h4"><spring:message code="template.form.additionalData" /></div>
                                <div class="form-group">
                                    <form:label path="constantSymbol"><spring:message code="template.form.constantSymbol" /></form:label><form:errors class="formError" path='constantSymbol' />
                                    <form:input type="text" class="form-control" path="constantSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="variableSymbol"><spring:message code="template.form.variableSymbol" /></form:label><form:errors class="formError" path='variableSymbol' />
                                    <form:input type="text" class="form-control" path="variableSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="specificSymbol"><spring:message code="template.form.specificSymbol" /></form:label><form:errors class="formError" path='specificSymbol' />
                                    <form:input type="text" class="form-control" path="specificSymbol" maxlength="10"/>
                                </div>
                                <div class="form-group">
                                    <form:label path="message"><spring:message code="template.form.message" /></form:label><form:errors class="formError" path='message' />
                                    <form:input type="text" class="form-control" path="message" maxlength="255" />
                                </div>
                            </div>
                            <div class="form-group col-12 text-center mt-sm-5">
                                <form:hidden path="id"/>
                                <button type="submit" class="btn btn-primary"><spring:message code="template.edit.form.editTemplate" /></button>
                            </div>
                        </div>
                    </form:form>
                </div>
            </div>
        </div>

    </layout:put>

    <layout:put block="scripts">

    </layout:put>
</layout:extends>

src/main/webapp/WEB-INF/templates/ib/ib_nav.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<div class="container">
    <nav>
        <div class="nav">
            <ul class="nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/ib/index"><spring:message code="ib.nav.accountsOverview" /></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ib/create-transaction"><spring:message code="ib.nav.payments" /></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ib/templates"><spring:message code="ib.nav.paymentTemplates" /></a>
                </li>
            </ul>
            <ul class="nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">${authorizedUser.firstName} ${authorizedUser.lastName}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/ib/profile"><spring:message code="ib.nav.accountSettings" /> <i class="fas fa-cog"></i></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:logout()"><spring:message code="ib.nav.logOut" /> <i class="fas fa-sign-out-alt"></i></a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

<jsp:include page="../sections/logout_form.jsp" />

src/main/webapp/WEB-INF/templates/ib/overview.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<layout:extends name="../base.jsp">
    <layout:put block="title" type="REPLACE">
        <title><spring:message code="ib.index.title" /></title>
    </layout:put>

    <layout:put block="styles">
        <link rel="stylesheet" href="/css/account.css">
    </layout:put>

    <layout:put block="content">

        <jsp:include page="ib_nav.jsp" />

        <div class="container-fluid lb-content-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-6 col-12">
                        <div class="h3"><spring:message code="ib.index.overviewLabel" /></div>
                        <table class="table table-hover table-sm">
                            <thead>
                                <tr>
                                    <th><spring:message code="ib.index.table.accountNumber" /></th>
                                    <th><spring:message code="ib.index.table.cardNumber" /></th>
                                    <th><spring:message code="ib.index.table.balance" /></th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:choose>
                                    <c:when test="${not empty accounts}">
                                        <spring:message code="ib.index.table.row.tooltip" var="rowTooltip" />
                                        <c:forEach items="${accounts}" var="account">
                                            <tr class="row-link" data-href="/ib/account/${account.id}" data-toggle="tooltip" data-placement="top" title="${rowTooltip}">
                                                <td>${account.accountNumber}</td>
                                                <td>${account.cardNumber}</td>
                                                <td>${account.formatedBalance}</td>
                                            </tr>
                                        </c:forEach>
                                    </c:when>
                                    <c:otherwise>
                                        <tr>
                                            <td colspan="3"><spring:message code="ib.index.table.noData" /></td>
                                        </tr>
                                    </c:otherwise>
                                </c:choose>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-5 col-md-6 col-12">
                        <form:form class="col-12 align-self-center" action="/ib/create-account" method="post" modelAttribute="newAccount">
                            <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <div class="h3"><spring:message code="account.create.form.label" /></div>
                                    <div class="form-group">
                                        <form:label path="currency"><spring:message code="account.create.form.currencyRequired" /></form:label><form:errors class="formError" path='currency' />
                                        <form:select class="form-control" path="currency" items="${currencies}" required="required" />
                                    </div>
                                </div>
                                <div class="form-group col-12 text-center mt-sm-5">
                                    <spring:message code="account.create.form.createAccount" var="createAccountLabel" />
                                    <input type="submit" class="btn btn-primary" value="${createAccountLabel}"/>
                                </div>
                            </div>
                        </form:form>
                    </div>
                </div>
            </div>
        </div>

    </layout:put>

    <layout:put block="scripts">
        <script>
            $(".row-link").click(function() {
                window.location = $(this).data("href");
            });
        </script>
    </layout:put>
</layout:extends>

src/main/webapp/WEB-INF/templates/ib/transaction_history.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<layout:extends name="../base.jsp">
    <layout:put block="title" type="REPLACE">
        <title><spring:message code="ib.account.title" /></title>
    </layout:put>

    <layout:put block="styles">
        <link rel="stylesheet" href="/css/account.css">
    </layout:put>

    <layout:put block="content">

        <jsp:include page="ib_nav.jsp" />

        <div class="container-fluid lb-content-wrapper">
            <div class="container">
                <div class="row mb-3">
                    <div class="col-12">
                        <div class="h3"><spring:message code="ib.account.accountInfo.label" /></div>
                        <div class="row">
                            <dt class="col-md-2"><spring:message code="ib.account.accountInfo.accountNumber" /></dt>
                            <dd class="col-md-10">${account.accountNumber}</dd>
                            <dt class="col-md-2"><spring:message code="ib.account.accountInfo.cardNumber" /></dt>
                            <dd class="col-md-10">${account.cardNumber}</dd>
                            <dt class="col-md-2"><spring:message code="ib.account.accountInfo.accountBalance" /></dt>
                            <dd class="col-md-10">${account.formatedBalance}</dd>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="h3"><spring:message code="ib.account.table.label" /></div>
                        <table class="table table-striped table-sm">
                            <thead>
                                <tr>
                                    <th><spring:message code="ib.account.table.createdOn" /></th>
                                    <th><spring:message code="ib.account.table.paymentType" /></th>
                                    <th><spring:message code="ib.account.table.amount" /></th>
                                    <th><spring:message code="ib.account.table.message" /></th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:choose>
                                    <c:when test="${not empty transactions}">
                                        <c:forEach items="${transactions}" var="transaction">
                                            <c:choose>
                                                <c:when test="${account.accountNumber == transaction.receiverAccountNumber}">
                                                    <tr>
                                                        <td>${transaction.createdDate}</td>
                                                        <td><spring:message code="ib.account.table.paymentType.incoming" /><br />${transaction.receiverAccountNumber} <- ${transaction.senderAccountNumber}</td>
                                                        <td class="transaction-profit">+ ${transaction.receivedAmount}</td>
                                                        <td>${transaction.message}</td>
                                                    </tr>
                                                </c:when>
                                                <c:otherwise>
                                                    <tr>
                                                        <td>${transaction.createdDate}</td>
                                                        <td><spring:message code="ib.account.table.paymentType.outgoing" /><br />${transaction.senderAccountNumber} -> ${transaction.receiverAccountNumber}</td>
                                                        <td class="transaction-cost">- ${transaction.sentAmount}</td>
                                                        <td>${transaction.message}</td>
                                                    </tr>
                                                </c:otherwise>
                                            </c:choose>
                                        </c:forEach>
                                    </c:when>
                                    <c:otherwise>
                                        <tr>
                                            <td colspan="4"><spring:message code="ib.account.table.noData" /></td>
                                        </tr>
                                    </c:otherwise>
                                </c:choose>
                            </tbody>
                        </table>
                    </div>
                </div>
                <c:if test="${not empty transactions}">
                    <div class="row">
                        <spring:message code="pagination.next" var="paginationNextLabel" />
                        <spring:message code="pagination.previous" var="paginationPreviousLabel" />
                        <nav class="col-12">
                            <ul class="pagination justify-content-center">
                                <li class="page-item">
                                    <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.previousOrFirst().pageNumber}&size=${pageRequest.pageSize}" aria-label="${paginationPreviousLabel}">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">${paginationPreviousLabel}</span>
                                    </a>
                                </li>
                                <c:forEach begin="${pageRequest.first().pageNumber}" end="${totalPages - 1}" var="position">
                                    <li class="page-item ${pageRequest.pageNumber == position ? 'active' : ''}">
                                        <a class="page-link" href="/ib/account/${account.id}?page=${position}&size=${pageRequest.pageSize}">${position + 1}</a>
                                    </li>
                                </c:forEach>
                                <c:if test="${pageRequest.next().pageNumber <= (totalPages - 1)}">
                                    <li class="page-item">
                                        <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.next().pageNumber}&size=${pageRequest.pageSize}" aria-label="${paginationNextLabel}">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">${paginationNextLabel}</span>
                                        </a>
                                    </li>
                                </c:if>
                            </ul>
                            <ul class="pagination justify-content-center">
                                <li class="page-item ${pageRequest.pageSize == 10 ? 'active' : ''}">
                                    <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.pageNumber}&size=10">10</a>
                                </li>
                                <li class="page-item ${pageRequest.pageSize == 20 ? 'active' : ''}">
                                    <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.pageNumber}&size=20">20</a>
                                </li>
                                <li class="page-item ${pageRequest.pageSize == 50 ? 'active' : ''}">
                                    <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.pageNumber}&size=50">50</a>
                                </li>
                                <li class="page-item ${pageRequest.pageSize == 100 ? 'active' : ''}">
                                    <a class="page-link" href="/ib/account/${account.id}?page=${pageRequest.pageNumber}&size=100">100</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </c:if>
            </div>
        </div>

    </layout:put>

    <layout:put block="scripts">

    </layout:put>
</layout:extends>

src/main/webapp/WEB-INF/templates/ib/user_profile.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<layout:extends name="../base.jsp">
    <layout:put block="title" type="REPLACE">
        <title><spring:message code="ib.profile.title" /></title>
    </layout:put>

    <layout:put block="styles">
    </layout:put>

    <layout:put block="content">

        <jsp:include page="ib_nav.jsp" />

        <jsp:include page="../sections/edit_profile_form.jsp" />

    </layout:put>

    <layout:put block="scripts">

    </layout:put>
</layout:extends>